# behaviors types
uint8 BEH_REGULAR=1
uint8 BEH_IMPASSIVE=2
uint8 BEH_SURPRISED=3
uint8 BEH_SCARED=4
uint8 BEH_CURIOUS=5
uint8 BEH_THREATENING=6

# behavior states
uint8 BEH_NO_ACTIVE=0
uint8 BEH_ACTIVE_1=1
uint8 BEH_ACTIVE_2=2

# behavior configuration
uint8 BEH_CONF_DEFAULT=0
uint8 BEH_CONF_CUSTOM=1
uint8 BEH_CONF_RANDOM_NORMAL=2
uint8 BEH_CONF_RANDOM_UNIFORM=3


uint8 type
uint8 state
uint8 configuration 
float32 duration
bool once
float32 vel
float32 dist
float32 social_force_factor
float32 goal_force_factor
float32 obstacle_force_factor
float32 other_force_factor


